name: 'ECA Config'
type: module
description: 'Config events.'
core_version_requirement: ^9 || ^10
package: ECA
dependencies:
  - eca:eca

# Information added by Drupal.org packaging script on 2022-09-30
version: '1.0.4'
project: 'eca'
datestamp: 1664529847
