name: 'ECA Config'
type: module
description: 'Config events.'
core_version_requirement: ^9 || ^10
package: ECA
dependencies:
  - eca:eca

# Information added by Drupal.org packaging script on 2022-12-12
version: '1.1.0'
project: 'eca'
datestamp: 1670843785
