views.area.display_link_plus:
  type: views_area
  label: 'Display Link Plus'
  mapping:
    display_id:
      type: string
      label: 'The id of the display that will be linked to.'
    label:
      type: label
      label: 'The label of the link.'
    class:
      type: string
      label: 'A CSS class to use on the link.'
    target:
      type: string
      label: 'Option to target a modal or off-screen dialog.'
    width:
      type: integer
      label: 'Width to use for the dialog.'
    append_destination:
      type: boolean
      label: 'Append destination query parameter'
    arguments_mapping:
      type: sequence
      label: 'Mapping of arguments into query.'
      sequence:
        type: display_link_plus_argument_mapping

display_link_plus_argument_mapping:
  type: mapping
  label: 'Argument mapping'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    query_string:
      type: string
      label: 'The query string to use for this argument'
    is_multiple:
      type: boolean
      label: 'If multiple values should be handled'
