# Schema for the configuration files of the field_suggestion module.

field_suggestion.settings:
  type: config_object
  label: 'Field Suggestion settings'
  mapping:
    collapsible:
      type: boolean
      label: 'Display suggestions list in drop-down view.'
    limit:
      type: integer
      label: 'The number of displayed values in a list of suggestions.'
    own:
      type: boolean
      label: 'Looking for suggestions only in entities of the current user.'
    fields:
      type: sequence
      label: 'Fields split by entity types'
      sequence:
        type: sequence
        label: 'Entity type identifiers'
        sequence:
          type: string
          label: 'Fields per entity type'

field_suggestion.type.*:
  type: config_entity
  label: 'Field suggestion type'
  mapping:
    id:
      type: string
      label: 'Field type name'
